[workspace]

members = [
  "crates/aa_get_started",
  "crates/connect",
  "crates/echo",
  "crates/tcp_json",
  "crates/tcp_flex",
  "crates/ensure",
  "crates/tinyhttp",
  "crates/tokio_tutorial",
]
